language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install libwebkitgtk-3.0-dev alex happy
  - cabal install Cabal
  - cabal install cabal-install
install:
  - PATH="$HOME/.cabal/bin:$PATH" cabal install gtk2hs-buildtools
  - PATH="$HOME/.cabal/bin:$PATH" cabal install --enable-tests
script:
  - PATH="$HOME/.cabal/bin:$PATH" cabal test
notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true
