sudo: required
dist: trusty

env:
 - CABALVER=1.24 GHCVER=7.10.1
 - CABALVER=1.24 GHCVER=7.10.2
 - CABALVER=1.24 GHCVER=7.10.3
 - CABALVER=1.24 GHCVER=8.0.1
 - CABALVER=head GHCVER=head

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install -y cabal-install-$CABALVER ghc-$GHCVER happy-1.19.5 alex-3.1.7
 - travis_retry sudo apt-get install -y libwebkitgtk-dev libwebkitgtk-3.0-dev libgirepository1.0-dev
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install Cabal cabal-install
 - cabal install gtk2hs-buildtools
 - git clone https://github.com/haskell-gi/haskell-gi.git
 - cabal install ./haskell-gi
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
 - cabal install --only-dependencies --enable-tests --force-reinstalls
 - cabal configure
 - cabal build
 - cabal haddock
 - cabal test
 - cabal clean
 - cabal sdist

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
